version: "3.9"

services:
  inventory-management-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: inventory_management_system
    restart: always
    volumes:
      - .:/inventory_management_system/
    command: >
      sh -c "python3 manage.py showmigrations &&
             python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - "9050:8000"
    container_name: inventory-management-web

    depends_on:
      - inventory_management_system_db
    stdin_open: true
    tty: true

  inventory_management_system_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Pa55word!
      POSTGRES_DB: inventory_management_system
    ports:
      - "5434:5432"
    container_name: inventory_management_system_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
